////////////////////////////////////////
// Aquí insertamos el código de áreas
////////////////////////////////////////


const horasLunes = [Area(11, "Ejercicio", 3, "#ff8080"),Area(1, "Dios", 2, "#003399"),Area(2, "Proyectos", 4, "#600080"),Area(3, "Aplicaciones", 2, "#008080"),Area(10, "Configuraciones", 0, "#009999")]
const horasMartes = [Area(1, "Dios", 2, "#003399"),Area(4, "Comisión", 4, "#600080"),Area(5, "Marca del perfil ESG", 2, "#008080"),Area(13, "Extra", 3, "#99004d"),Area(10, "Configuraciones", 0, "#009999")]
const horasMiercoles = [Area(1, "Dios", 7, "#003399"),Area(2, "Proyectos", 2, "#600080"),Area(13, "Extra", 2, "#99004d"),Area(9, "Estrategia con mi chico", 0, "#2a0080"),Area(10, "Configuraciones", 0, "#009999")]
const horasJueves = [Area(4, "Comisión", 2, "#600080"),Area(5, "Marca del perfil ESG", 2, "#008080"),Area(6, "Fortalecer contactos", 2, "#008080"),Area(7, "Cursos & workshops", 2, "#600080"),Area(13, "Extra", 1, "#99004d"),Area(9, "Estrategia con mi chico", 0, "#2a0080"),Area(10, "Configuraciones", 0, "#009999")]
const horasViernes = [Area(1, "Dios", 2, "#003399"),Area(3, "Aplicaciones", 2, "#008080"),Area(6, "Fortalecer contactos", 2, "#008080"),Area(7, "Cursos & workshops", 2, "#600080"),Area(13, "Extra", 3, "#99004d"),Area(10, "Configuraciones", 0, "#009999")]
const horasSabado = [Area(11, "Ejercicio", 3, "#ff8080"),Area(1, "Dios", 1, "#003399"),Area(7, "Cursos & workshops", 2, "#600080"),Area(13, "Extra", 3, "#99004d"),Area(10, "Configuraciones", 0, "#009999")]
const horasDomingo = [Area(1, "Dios", 2, "#003399"),Area(13, "Extra", 3, "#99004d"),Area(10, "Configuraciones", 0, "#009999")]
const nada = ""
////////////////////////////////////////

let areasDeHoy = horasLunes

/////////////////////////////////////////////////////////////
// Aquí insertamos el código de actividades
// ORM: https://colab.research.google.com/drive/1jD08kTPmRHfKIAopE2iv1sX3jrinLBEo?usp=sharing
// Excel: https://docs.google.com/spreadsheets/d/15bKo-qgFv_W6fmUVCgoHzCvpWKCCsYjxDZL_QqOWxTc/edit?usp=sharing
/////////////////////////////////////////////////////////////

const actividades11 = [Actividad('11', 'Gym', '0', '1', '#ff8080', 'white', '¡Hola hermosa! ¡Como ayer fuiste a la fundación, hoy puedes ir al Gym si quieres! Empieza tu día viendo influencers fit que te gusten y así te motivas!', '<a target="_blank" href="./img/gym.png"><img src="./img/gym.png" alt="Dos mujeres riéndose sentadas en el gym." style="width:100%" /></a></br>', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'),Actividad('11', 'Natación', '0', '2', '#ff8080', 'white', 'La otra semana probamos el viernes mi corazón.', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan')]
const actividades1 = [Actividad('1', 'Congregarme', '1', '2', '#003399', 'white', 'Hola corazón. Hoy tienes alabanza por la tardecita. Te amo preciosa.', 'nan', 'Horarios y sedes IDMJI', 'https://idmji.org/direcciones/', 'nan', 'nan', 'nan', 'nan'),Actividad('1', 'Oración y lectura', '0', '1', '#003399', 'white', 'Trata de llegar tempranito para orar y leer un tris amada mía.', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'),Actividad('1', 'Servicio', '1', '3', '#003399', 'white', 'Esta semanita fuiste muy dispuesta, gran trabajo amor.', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'),Actividad('1', 'Fundación', '1', '5', '#003399', 'white', 'Lo que has hecho por la fundación también me parece precioso.', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'),Actividad('1', 'IDMJI-EN', '0', '4', '#003399', 'white', 'Estos son los sábados.', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan')]
const actividades2 = [Actividad('2', 'Maqueta en baja libro infantil', '0', '1', '#600080', 'white', '¡Amor! igual a como conversamos ayer para el otro proyecto ¿Por qué no piensas una maqueta en muy baja resolución que estructure la narrativa general.</br></br>Para el tema pedagógico es importante que consideres <u>un aprendizaje clave</u> y sólo uno, para los niños. No es tan pedagógico empacar muchas cosas que aprender en un sólo bloque. Yo te propongo que lo inspires en el Marshmellow test sobre delayed gratification, ese es para niños de 4 o 5 años. Podrías pensar una narrativa que materialice esa noción de autocontrol.</br></br>Te dejo un video enlazado a la foto. Y otro video sobre planear tu historia si quieres verlos.', '<a target="_blank" href="https://youtu.be/M0yhHKWUa0g"><img src="./img/marshmellow.png" alt="Test del masmelo" style="width:100%" /></a>', 'Video: plan your book', 'https://youtu.be/knA9AlI3R8g?t=108', 'nan', 'nan', 'nan', 'nan'),Actividad('2', 'Doméstika: dibujo anatómico', '0', '2', '#600080', 'white', 'Preciosa! sigue con tu curso de dibujo anatómico. Hoy en particular, si quieres seguir con tu curso, tendrías que dedicarle tiempito de tus 3 horas extra. Está bien.. puedes seguirlo la otra semanita. Aunque no pierdas el ritmo!', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan')]
const actividades3 = [Actividad('3', 'Mapear vacantes en LinkedIn', '0', '1', '#008080', 'white', '¡Amada! Hoy haz trabajo simultáneo de esto y de fortalecimiento de red.</br></br>Te propongo que para aplicaciones busques (sólo mapear por ahora, y la otra semana aplicas) ofertas de trabajo en LinkedIn para posiciones de sostenibilidad, ESG, etc.</br></br>Pero mientras haces eso, ¡ve haciendo lo que te indico en fortalecer contactos! Ten dos tablas separadas, pero ve haciendo las dos cosas juntitas.', '<a target="_blank" href="./img/linked2.png"><img src="./img/linked2.png" alt="Captura de pantalla búsqueda ESG en trabajos LinkedIn" style="width:100%" /></a>', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'),Actividad('3', 'Agendar asesoría CV en CTP', '0', '2', '#008080', 'white', 'Maravilloso que hayas preguntado! De esto estamos pendientes la otra semana. Te amo!', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan')]
const actividades4 = [Actividad('4', 'Creación de obra', '0', '1', '#600080', 'white', 'Preciosa, recuerda nunca parar de producir obra nueva. Puedes intentar aplicar algo de lo que has aprendido en tu curso de dibujo anatómico hasta ahora en una pieza. O bien, puedes buscar nueva inspiración. Te dejo tu moodboart.', '<a target="_blank" href="./img/mood.png"><img src="./img/mood.png" alt="Captura de pantalla del grupo MoodboArt en Waa" style="width:100%" /></a></br><a target="_blank" href="./img/botero.jpg"><img src="./img/botero.jpg" alt="Museo Botero" style="width:100%" /></a>', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'),Actividad('4', 'Reunión estrategia de contenido orientado a ventas', '0', '2', '#600080', 'white', 'Amor agenda a tu chico para que podamos crear una estrategia de contenido para Entropía Cromática que esté orientada a vender obra, al igual que a fortalecer tu marca. Puede ser la otra semana!', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan')]
const actividades5 = [Actividad('5', 'Curso Palermo', '0', '2', '#008080', 'white', '¡Vida, mientras te aprueban apoyo financiero para el curso de ESG, podrías ir comenzando con el curso de la Universidad de Palermo! Está buenísimo que tengas así como tienes una cola de cursos en Domestika, una fila de cursos para tu perfil ESG 🤍 Te dejo el curso enlazado en la imagen.', '<a target="_blank" href="https://www.coursera.org/learn/etica-gobierno-corporativo"><img src="./img/palermo.png" alt="Captura de pantalla de curso universidad e palermo en coursera." style="width:100%" /></a>', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'),Actividad('5', 'Contenido: recordarles que existo', '0', '1', '#008080', 'white', 'Por lo pronto comencemos los cursos. Pero ya nos iremos pensando en qué publicar en LinkedIn para recordarle al mundo que existes y eres una profesional valiosísima!', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'),Actividad('5', 'Esperar respuesta Apoyo Financiero', '0', '1', '#008080', 'white', 'Tamos a la espera de este hasta junio 13.', '<a target="_blank" href="./img/esg.png"><img src="./img/esg.png" alt="Captura de pantalla del curso de ESG" style="width:100%" /></a>', 'Coursera ESG', 'https://www.coursera.org/specializations/materiality-esg-factors', 'Carpeta taller ESG', 'https://drive.google.com/drive/folders/1Ml0LH5pWT8PSN9vOIenDOLFNdFwGW83Z?usp=sharing', 'nan', 'nan')]
const actividades6 = [Actividad('6', 'Mapear organizaciones', '0', '1', '#008080', 'white', 'Preciosa, mientras haces lo de mapear vacantes, ve armando la tablita o el board de organizaciones que tienen departamentos de sostenibilidad en Colombia. Buscan en LinkedIn las empresas así como te muestro en la foto. ¡Que sobre y no que falte! Toooodas en las que eventualmente te gustaría trabajar ponlas!</br></br>¡También puedes buscar en las 100 empresas más grandes de Colombia! Te dejo el enlace abajo.', '<a target="_blank" href="./img/empresas.png"><img src="./img/empresas.png" alt="Captura de pantalla buscador de LinkedIn" style="width:100%" /></a>', '100 empresas más grandes de Colombia', 'https://www.larepublica.co/especiales/las-1-000-empresas-mas-grandes-de-2022/ecopetrol-lidera-las-100-empresas-mas-grandes-de-colombia-en-2022-3642520', 'nan', 'nan', 'nan', 'nan')]
const actividades7 = [Actividad('7', 'Ideas para curso', '0', '1', '#600080', 'white', 'Como ayer estuviste sólamente trabajando en obra, hoy puedes dedicar un tiempo a pensarte una propuesta de curso para ofrecer por Instagram como MVP. Piensa en un tipo de <b>experiencia + aprendizaje</b>, en lugar de sólo aprendizaje. Puede ser en un café bonito experiencia tardeada, o un taller de dibujo anatómico en un entorno más "artsy" como una sala galería.</br></br>Puedes hacer un brainstorming de ideas para <u>workshops de una tarde</u> y otra de <u>cursos de varias sesiones</u> con una habilidad clara en mente.', '<a target="_blank" href="./img/workshop.png"><img src="./img/workshop.png" alt="Personas pintando en un taller de una tarde." style="width:100%" /></a>', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'),Actividad('7', 'Buscar espacio y cotizarlo', '0', '2', '#600080', 'white', 'La otra semana me pides el contacto de Jessica Held que me pasó Ángela. Ella es dueña de un café lindo. Y también podemos ir cotizando en lugares tipo hotel luxurious, o espcios galería independiente, etc.', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan')]
const actividades8 = [Actividad('8', 'Columnas de la tabla de becas', '0', '1', '#660033', 'white', 'Hermosa, yo creo que si armamos una tablita y comenzamos a consolidar ahí todas las oportunidades de becas que hemos visto ahí, por insta, y de más fuentes, sería top. Te dejo la lista de nuestros países favoritos.  Por lo pronto con que estructures unas columnas, yo creo que chuleamos. No olvides compartirmelo :3 Te amo!', '<ul><li>Inglaterra &lt;3</li><li>Suiza &lt;3</li><li>Noruega*</li><li>Italia &lt;3</li><li>Alemania &lt;3</li><li>España &lt;3</li><li>Francia</li><li>Canadá &lt;3</li><li>Suencia*</li><li>Dinamarca*</li><li>Austria &lt;3</li><li>Nueva Zelanda</li><li>Australia</li></ul>', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan')]
const actividades12 = [Actividad('12', 'Ir a la U a nadar', '0', '1', '#00e6ac', 'white', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan')]
const actividades13 = [Actividad('13', 'Curso de dibujo anatómico', '0', '0', '#99004d', 'white', 'Si quieres, como te veo muy engomada, puedes dedicar tiempo extra a esto, o lo que prefieras amor.', '<a target="_blank" href="https://www.domestika.org/es/courses/area/184-dibujo-anatomico"><img src="./img/dibujo.png" alt="Imágen del curso de dibujo anatómico en domestika" style="width:100%" /></a>', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'),Actividad('13', 'Lectura', '0', '3', '#99004d', 'white', '¡Ve buscando qué libro te gustaría leer! Si quieres, la otra semana vamos a la biblioteca de la U y pides prestado el libro que quieras!</br></br> Te dejo enlazado en la imágen la página de la biblioteca.', '<a target="_blank" href="https://biblioteca.uniandes.edu.co/"><img src="./img/leer.jpg" alt="Mujer leyendo en la ventana." style="width:100%" /></a>', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'),Actividad('13', 'Journaling', '0', '7', '#99004d', 'white', 'También puedes escribir en tu journal.', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'),Actividad('13', 'Tiempo con mi chico', '0', '8', '#99004d', 'white', 'Hoy ño creo que nus veamus :(', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'),Actividad('13', 'Ocio', '0', '6', '#99004d', 'white', 'Tienes tiempo si quieres ver algo en streaming hoy.', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'),Actividad('13', 'Baile', '0', '1', '#99004d', 'white', 'Podrías ver qué clases hay hoy, si no se te cruza con la i.', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'),Actividad('13', 'Arpa', '1', '4', '#99004d', 'white', 'Esa pieza nueva está preciosaaaaaaaaa', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'),Actividad('13', 'Salir con amigos', '0', '5', '#99004d', 'white', 'Para cuando cuadres depués.', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'),Actividad('13', 'Canto', '0', '2', '#99004d', 'white', 'Para después.', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan')]
const actividades9 = [Actividad('9', 'Imprimir tracker', '0', '1', '#2a0080', 'white', 'Si no lo imprimiste ayer, recuerda imprimir tu tracker, puede ser de venida del gym amor.', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan')]
const actividades10 = [Actividad('10', 'Configurar colores', '1', '1', '#009999', 'white', '¡Amor! Todos los días yo renuevo los datos de tu board. Para configurar los colores sólo es necesario que en el excel que te comparto a continuación tú modifiques las columnas de color. Para escoger el código correspondiente puedes usar la herramienta de elección de color y copiar el hexadecimal.</br></br>Los colores que debes modificar están en la pestaña "areas" y "actividades".', '<a target="_blank" href="./img/color.png"><img src="./img/color.png" alt="Captura de pantalla de w3 color picker" style="width:100%" /></a>', 'Excel de datos ', 'https://docs.google.com/spreadsheets/d/15bKo-qgFv_W6fmUVCgoHzCvpWKCCsYjxDZL_QqOWxTc/edit?usp=sharing', 'Paleta de Colores', 'https://www.w3schools.com/colors/colors_picker.asp', 'nan', 'nan'),Actividad('10', 'Configurar actividades', '1', '2', '#009999', 'white', 'Para configurar las actividades sólo debes editar en el excel la tabla en la pestaña "actividades". Tu novio carga todos los días los datos a la aplicación para que aparezcan.', '<a target="_blank" href="./img/actividades.png"><img src="./img/actividades.png" alt="Captura de pantalla de tabla de actividades" style="width:100%" /></a>', 'Excel de datos ', 'https://docs.google.com/spreadsheets/d/15bKo-qgFv_W6fmUVCgoHzCvpWKCCsYjxDZL_QqOWxTc/edit?usp=sharing', 'nan', 'nan', 'nan', 'nan'),Actividad('10', 'Configurar áreas', '1', '3', '#009999', 'white', 'En el excel en la pestaña areas puedes encontrar la información de las áreas. Tu novio actualiza los datos todos los días desde el excel para que te aparezcan de acuerdo a lo que pusiste. ¡Si tienes cualquier duda me puedes decir!', '<a target="_blank" href="./img/areas.png"><img src="./img/areas.png" alt="Captura de pantalla de tabla de areas" style="width:100%" /></a>', 'Excel de datos ', 'https://docs.google.com/spreadsheets/d/15bKo-qgFv_W6fmUVCgoHzCvpWKCCsYjxDZL_QqOWxTc/edit?usp=sharing', 'nan', 'nan', 'nan', 'nan'),Actividad('10', 'Marco', '1', '4', '#009999', 'white', 'Todo está alineado con el figma. Te lo dejo aquí.', '<a target="_blank" href="./img/board.png"><img src="./img/board.png" alt="Captura de pantalla de baord de areas" style="width:100%" /></a> </br></br> <a target="_blank" href="./img/board1.png"><img src="./img/board1.png" alt="Captura de pantalla de baord de areas" style="width:100%" /></br></br><a target="_blank" href="./img/board2.png"><img src="./img/board2.png" alt="Captura de pantalla de baord de areas" style="width:100%" /></br></br><a target="_blank" href="./img/board3.png"><img src="./img/board3.png" alt="Captura de pantalla de baord de areas" style="width:100%" /></br></br><a target="_blank" href="./img/board4.png"><img src="./img/board4.png" alt="Captura de pantalla de baord de areas" style="width:100%" /></br></br>', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan')]
const actividades14 = [Actividad('14', 'Identify hanging pieces', '0', '1', '#cccccc', '#404040', 'Amor, una pieza indefensa o hanging piece es una pieza que no está siendo defendida por nadie. La competencia que vamos a entrenar es que identifiques esas piezas en cada turno que tengas.', '<a target="_blank" href="https://www.chess.com/terms/hanging-piece-chess#:~:text=A%20hanging%20piece%20is%20a,for%20being%20exposed%20to%20capture)."><img src="./img/chess1.png" alt="Hanging bishop in board." style="width:100%" /></a></br>', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan')]

const diccionarioActividades = {
  11 : actividades11,
  1 : actividades1,
  2 : actividades2,
  3 : actividades3,
  4 : actividades4,
  5 : actividades5,
  6 : actividades6,
  7 : actividades7,
  8 : actividades8,
  12 : actividades12,
  13 : actividades13,
  9 : actividades9,
  10 : actividades10,
  14 : actividades14
}
/////////////////////////////////////////

let actividadesVisibles = diccionarioActividades[2]


////////// SIMULAR ALGÚN DÍA /////////
function simularDia(diaOriginal){
	diaOriginal = diaOriginal; // Aquí podemos simular un día si se desea 0 es domingo, 1 es lunes... 6 es sábado
	return diaOriginal;
}